{{- $secretStoreName := include "ns.secretStoreName" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.djangoSecretKey }}
spec:
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.djangoSecretKey }}
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: django-{{ .Values.env.HMD_INSTANCE_NAME }}-{{ .Values.env.HMD_REPO_NAME }}-{{ .Values.env.HMD_DID }}
        property: secret-key
