{{- $secretStoreName := include "ns.secretStoreName" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "k8sDbSecretName" . }}
spec:
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ template "k8sDbSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ template "awsDbSecretName" . }}
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: {{ template "awsDbSecretName" . }}
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: {{ template "awsDbSecretName" . }}
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: {{ template "awsDbSecretName" . }}
        property: port
