{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hmd-app-neuronsphere.serviceAccountName" . }}
  labels:
    {{- include "hmd-app-neuronsphere.labels" . | nindent 4 }}
{{- end }}
