# Generated by Django 5.0.14 on 2026-02-06 21:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeSetDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target_deployment_set", models.CharField(max_length=100)),
                ("target_environment", models.CharField(max_length=50)),
                (
                    "content",
                    models.JSONField(
                        default=list, help_text="List of changes in ChangeSet format"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changeset_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_environment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "default_deployment_set",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "default_view",
                    models.CharField(
                        choices=[("table", "Table View"), ("dag", "DAG View")],
                        default="table",
                        max_length=20,
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_bom", "View BOM"),
                            ("view_instance", "View Instance"),
                            ("create_changeset", "Create ChangeSet"),
                            ("apply_changeset", "Apply ChangeSet"),
                            ("view_deployment", "View Deployment"),
                            ("view_logs", "View Logs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Target resource (e.g., 'dev:base-vpc')",
                        max_length=200,
                    ),
                ),
                (
                    "details",
                    models.JSONField(default=dict, help_text="Full request details"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        help_text="Request correlation ID for tracing",
                        max_length=36,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        help_text="Request duration in milliseconds", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="deployments_user_id_f5ce8e_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="deployments_action_9e3930_idx",
                    ),
                    models.Index(
                        fields=["target", "-timestamp"],
                        name="deployments_target_f89c98_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserEnvironmentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        db_index=True,
                        help_text="Environment type (e.g., 'dev', 'test', 'prod')",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("deployer", "Deployer"),
                            ("admin", "Admin"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "environment"],
                "indexes": [
                    models.Index(
                        fields=["user", "role"], name="deployments_user_id_cf7582_idx"
                    )
                ],
                "unique_together": {("user", "environment")},
            },
        ),
    ]
